name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint HTML files
        run: npx htmlhint "src/**/*.html"

      - name: Lint CSS files
        run: npx stylelint "styles/**/*.css"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build website with Parcel
        run: npm run build
